<a href="https://colab.research.google.com/github/alexlopespereira/idp_mestrado/blob/main/Aulas/Aula4/Aula4_Exercicio_Extra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 4 - Exercícios Extra - Python e NumPy

### Onde buscar informações sobre as funções do Numpy
[https://numpy.org/doc/stable/search.html](https://numpy.org/doc/stable/search.html)

In [ ]:
import numpy as np

### 4.5 Escreva uma função Python para selecionar os elementos de um array que são ao mesmo tempo: maiores que 10, menores que 50 e multiplos de 3.
#### Exemplo:  para um array([0, 12, 45, 34, 99])
#### Resultado esperado: array([12, 45])
#### Dica: Reveja a explicação dos slides 22 e 23 da aula 4.

In [ ]:
def filter_array(arr):
    """retorne um array numpy contendo números maiores que 10,
       menores que 50 e multiplos de 3
    """
    pass

In [ ]:
## Faça seus testes aqui
inarr = np.array([0, 12, 45, 34, 99])
print(filter_array(inarr))  # [12 45]

In [ ]:
# Validação
inarr = np.array([0, 12, 45, 34, 99])
outarr = np.array([12, 45])
assert np.array_equal(filter_array(inarr), outarr)
print("Exercício 4.5 OK!")

### 4.6 Escreva uma função Python para criar um array numpy 2D com 1s nos elementos das bordas e com 0s no interior. O tamanho do array deve ser parametrizável.
#### Exemplo:  para um n=3
#### Resultado esperado: array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])
#### Dica: Crie um array bi-dimensional de zeros (com a função np.zeros) e preencha as bordas com 1s, ou crie um array de 1s (com a função np.ones) e preencha o interior com zeros.

In [ ]:
def create_array(n):
    """retorne um array 2d preenchido com 1s nas bordas e 0s no interior
    """
    pass

In [ ]:
## Faça seus testes aqui
print(create_array(3))
# [[1. 1. 1.]
#  [1. 0. 1.]
#  [1. 1. 1.]]

In [ ]:
# Validação
a3 = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=float)
a6 = np.array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])
assert np.array_equal(create_array(3), a3)
assert np.array_equal(create_array(6), a6)
print("Exercício 4.6 OK!")

### 4.7 Escreva uma função Python para selecionar dentre os elementos de um array (arr1 passado como argumento) aquele que mais se aproxima de um determinado valor N passado como argumento da função.
#### Se houver dois elementos equidistantes de N e forem os mais próximos de N, retorne o menor. Ou seja, para [1, 3, 4] e N=2, retorne 1.
#### Não use laços (loops), use funções Numpy.
#### Exemplo:  para um array([0, 12, 45, 34, 99]) e N=20
#### Resultado esperado: 12
#### Dica 1: Use as funções np.abs, ndarray.argmin e ndarray.sort
#### Dica 2: Comece ordenando o array com a função ndarray.sort
#### Dica 3: Crie um array com a diferença entre cada elemento do array de entrada (arr1) e o número N, e chame-o de dif.
#### Dica 4: Calcule o valor absoluto do array dif, e armazene-o numa variável chamada absoluto.
#### Dica 5: De maneira genérica, use uma função numpy para retornar o índice do menor valor de um array, e guarde-o numa variavel chamada index.
#### Dica 6: Retorne o elemento do array arr1 na posição guardada em index.
#### Curiosidade: Por que se faz necessário ordenar o array arr1?

In [ ]:
def get_closest(arr1, N):
    """retorne o elemento do array que mais se aproxima de N.
       No caso de dois elementos equidistantes, retorne o menor.
    """
    pass

In [ ]:
## Faça seus testes aqui
inarr = np.array([3, 6, 1, 4])
print(get_closest(inarr, 2))  # 1

In [ ]:
# Validação
inarr = np.array([3, 6, 1, 4])
assert get_closest(inarr, 2) == 1
inarr2 = np.array([0, 12, 45, 34, 99])
assert get_closest(inarr2, 20) == 12
print("Exercício 4.7 OK!")